#!/bin/bash
    clear
    figlet "BADVPN" | lolcat
    echo -e "╔═══════════════════════════•⊱✦⊰•═══════════════════════════╗" | lolcat
    echo -e "  \033[1;37mATIVE O BADVPN PRIMEIRO ANTES DE ENTRAR NO GERENCIADOR BADVPN \033[0m"
    echo -e "╚═══════════════════════════•⊱✦⊰•═══════════════════════════╝" | lolcat
    echo -e "  \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN PRO (64 BITS) $stsu\033[0m"
    echo -e "  \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[1;33mATIVAR BADVPN PRO (ARM ORACLE)\033[0m"
    echo -e "° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °" | lolcat
    echo -e "  \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[1;33mGERENCIAR BADVPN\033[0m"
    echo -e "° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °" | lolcat
    echo -e "  \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "╚═══════════════════════════•⊱✦⊰•═══════════════════════════╝" | lolcat
			tput civis
			echo -ne " \033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m: ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			badpro
			;;
			2 | 02)
			badvpn3
			;;
			3 | 03)
			badvpn1
			;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	fun_conexao
}
