#!/bin/bash
    clear
    figlet " PAINEL-WEB" | lolcat
    echo -e "╔═══════════════════════════•⊱✦⊰•═══════════════════════════╗" | lolcat
    echo -e " \033[1;37mINSTALAR PAINEL WEB APENAS EM SERVIDOR 64 BITS \033[0m"
    echo -e "╚═══════════════════════════•⊱✦⊰•═══════════════════════════╝" | lolcat
    echo -e " \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[1;33mINSTALAR PAINEL\033[0m"
	echo -e "° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °" | lolcat
    echo -e " \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[1;33mALTERAR PORTA APACHE(PADRAO: 80) \033[0m"
    echo -e " \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[1;33mGERENCIAR PAINEL\033[0m"
    echo -e "° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °" | lolcat
    echo -e " \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 04 •\033[1;34m]\033[1;37m ➩  \033[1;33mSINCRONIZAR SERVIDOR\033[0m"
    echo -e "° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° ° °" | lolcat
    echo -e " \033[01;31m\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
    echo -e "╚═══════════════════════════•⊱✦⊰•═══════════════════════════╝" | lolcat
			tput civis
			echo -ne " \033[1;31m➤ \033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m: ";
			read x
			tput cnorm
			clear
			case $x in
			1 | 01)
			bash <(wget -qO- https://raw.githubusercontent.com/zxL0rdxz/SSH-WEB/main/123.sh)
			;;
			2 | 02)
			apache2menu
			;;
			3 | 03)
			pweb
			;;
			4 | 04)
			bash <(wget -qO- https://raw.githubusercontent.com/zxL0rdxz/SSH-WEB/main/sincpainel.sh)
			;;
			0 | 00)
			clear
			menu
			;;
			*)
			echo -e "\033[1;31mOpcao invalida !\033[0m"
			sleep 2
			;;
			esac
		done
	}
	fun_conexao
}
